name: Rust
on:
  push:
    branches: [ "main" ]
    paths:
      - 'src/account/**'
      - 'src/central/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'src/account/**'
      - 'src/central/**'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install DFX
      uses: dfinity/setup-dfx@main

    - name: Start DFX
      run: dfx start --background

    - name: Setup DFX identity
      run: |
        mkdir -p ~/.config/dfx/identity/default
        echo '-----BEGIN PRIVATE KEY-----
        MFMCAQEwBQYDK2VwBCIEIJ5MV1cHWxGG+tR3QbO7t+MhiWx7TzRLvX1Q9pFHFcAN
        oSMDIQCDuaUeEk4R5y3eBHyBNzHGeKafyC3cK1Wd+kY5T4OsRg==
        -----END PRIVATE KEY-----' > ~/.config/dfx/identity/default/identity.pem
        chmod 600 ~/.config/dfx/identity/default/identity.pem

    - name: Create canisters
      run: dfx canister create --all

    - name: Generate wasm artifacts
      run: dfx build

    - name: Run tests
      run: cargo test --verbose

    - name: Stop DFX
      if: always()
      run: dfx stop