name: Rust
on:
  push:
    branches: [ "main" ]
    paths:
      - 'src/account/**'
      - 'src/central/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'src/account/**'
      - 'src/central/**'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install DFX
      uses: dfinity/setup-dfx@main

    - name: Start DFX
      run: dfx start --background

    - name: Create canisters
      run: |
        dfx identity new default --force
        dfx canister create --all

    - name: Generate wasm artifacts
      run: dfx build

    - name: Run tests
      run: cargo test --verbose

    - name: Stop DFX
      if: always()  # Run even if previous steps fail
      run: dfx stop
